In [16]:
import pandas as pd
import numpy as np
import plotly.express as px

In [17]:
pokemon_df = pd.read_csv('C:/Users/Carlos/Documents/DarkDex/darkdex/archives/Pokemon.csv')

In [18]:
pokemon_df = pokemon_df.rename(
    columns={
        "#": "id",
        "Name": "name",
        "Attack": "attack",
        "Defense": "defense",
        "Sp. Atk": "sp_attack",
        "Sp. Def": "sp_defense",
        "HP": "hp",
        "Speed": "speed",
    }
)

In [19]:
pokemon_df["offensive_power"] = pokemon_df["attack"] + pokemon_df["sp_attack"]
pokemon_df["defensive_power"] = pokemon_df["defense"] + pokemon_df["sp_defense"]
pokemon_df["bulk"] = pokemon_df["hp"] + pokemon_df["defensive_power"]
pokemon_df["speed_score"] = pokemon_df["speed"]

In [20]:
counts_df = pokemon_df.groupby('id').size().reset_index(name='Total_Count')

In [22]:
display(counts_df[counts_df['Total_Count'] > 1])

      id  Total_Count
2      3            2
5      6            3
8      9            2
14    15            2
17    18            2
..   ...          ...
680  681            2
709  710            4
710  711            4
718  719            2
719  720            2

[65 rows x 2 columns]

In [11]:
display(pokemon_df)

,#,name,Type 1,Type 2,Total,hp,attack,defense,sp_attack,sp_defense,speed,Generation,Legendary,offensive_power,defensive_power,bulk,speed_score
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,114,114,159,45
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,142,143,203,60
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,182,183,263,80
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,222,243,323,80
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,112,93,132,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,200,300,350,50
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,320,220,270,110
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,260,190,270,70
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,330,190,270,80
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,240,210,290,70

In [12]:
def plot_distribution(df, identificacao, x, y=None, z=None, color=None, jitter_1d=0.02):

    df = df.copy()

    if z is not None and y is not None:
        fig = px.scatter_3d(
            df,
            x=x,
            y=y,
            z=z,
            color=color,
            opacity=0.8,
            hover_name=identificacao,
            title="Visualização 3D Interativa"
        )

    elif y is not None:
        fig = px.scatter(
            df,
            x=x,
            y=y,
            color=color,
            opacity=0.8,
            hover_name=identificacao,
            title="Visualização 2D Interativa"
        )

    else:
        df["_y_dummy"] = np.random.uniform(
            low=-jitter_1d,
            high=jitter_1d,
            size=len(df)
        )

        fig = px.scatter(
            df,
            x=x,
            y="_y_dummy",
            color=color,
            opacity=0.8,
            hover_name=identificacao,
            title="Visualização 1D Interativa"
        )

        fig.update_yaxes(visible=False)

    fig.update_traces(marker=dict(size=7))
    fig.update_layout(
        width=900,
        height=600,
        legend_title=color
    )

    fig.show()

In [13]:
plot_distribution(pokemon_df, 'name', 'offensive_power')